Custom inputs and validations.
micaelomota/live-youtube-web-app pull request #3
Opened 2024-02-05 07:28 UTC by iarlen-reis

# features
- [feat: created ButtonForm, InputForm and SelectorForm components to reuse code and styling.](https://github.com/micaelomota/live-youtube-web-app/commit/ee688ddd9dfcd1664ff95ee2809da4100ac660e7)
- [feat: Adding validations in the name, target, unity, deadline and currentValue fields on the NewTargetScreen page.](https://github.com/micaelomota/live-youtube-web-app/commit/08023dd72a0ff0f33c13794c6645c09a4cef32b5)
- [refactor: removing the created_At and updated_At logic from the new target page and moving it to the context.](https://github.com/micaelomota/live-youtube-web-app/commit/7ed81de8dc66c1212e17f2645f6442231d40204e)

# fixes
- [fix: remove node modules from git](https://github.com/micaelomota/live-youtube-web-app/commit/c35ec6a84e165abf74257b947ba56190b9aa69e9)

# chores
- [chore: installing and configuring tailwind](https://github.com/micaelomota/live-youtube-web-app/commit/92c63bf38f86be6f290ca91c7572b62b95c80363)

2024-02-06 17:02 UTC, micaelomota commented
@iarlen-reis tem como remover os arquivos do node e fazer um rebase de main para pegar o .gitignore

2024-02-06 17:18 UTC, iarlen-reis commented
> @iarlen-reis tem como remover os arquivos do node e fazer um rebase de main para pegar o .gitignore

> @micaelomota o .gitignore foi adicionado e a node modules foi removido no primeiro commit da PR

[fix: remove folder node modules](https://github.com/micaelomota/live-youtube-web-app/commit/c35ec6a84e165abf74257b947ba56190b9aa69e9)

2024-02-06 18:11 UTC, iarlen-reis commented
> @iarlen-reis tem como remover os arquivos do node e fazer um rebase de main para pegar o .gitignore

> @micaelomota conflitos resolvidos.

2024-02-19 00:15 UTC, micaelomota requested changes

2024-02-19 00:15 UTC, micaelomota commented on frontend/src/context/TargetContext.tsx
> +    }, [targets])
precisa fazer um rebase, a gente já está usando o firestore database

2024-02-19 01:08 UTC, micaelomota commented
Estou fechando porque fiz o rebase e mesclei no meu repo.  assiste a live https://youtube.com/live/MOu_Alj2VXI?feature=share

2024-02-19 01:08 UTC, closed without merging